name: rac_road
description: A Flutter project.


version: 1.0.5+6

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.1
  page_transition: ^2.0.9
  percent_indicator: ^4.2.2
  http: ^0.13.5
  intl: ^0.17.0
  buddhist_datetime_dateformat_sns: ^1.0.7
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  get: ^4.6.5
  like_button: ^2.0.4
  expandable: ^5.0.1
  flutter_speed_dial: ^6.0.0
  rename: ^2.0.1
  auto_size_text: ^3.0.0
  google_sign_in: ^5.4.2
  smooth_page_indicator: ^1.0.0+2
  form_field_validator: ^1.1.0
  im_stepper: ^1.0.1+1
  geolocator: ^10.0.0
  geocoding: ^2.0.5
  url_launcher: ^6.1.7
  flutter_rating_bar: ^4.0.1
  grouped_list: ^5.1.2
  gallery_saver: ^2.3.2
  pull_to_refresh: ^2.0.0
  chips_choice: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  expandable_page_view: ^1.0.17
  timeago: ^3.3.0
  syncfusion_flutter_calendar: ^20.4.53
  flutter_markdown: ^0.6.17
  change_app_package_name: ^1.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcer.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/imgs/logos/
    - assets/imgs/markets/
    - assets/icons/
    - assets/

