// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY6DWCmM_qZyV590ymb4x-OcyO4HzMWbk',
    appId: '1:393321453673:web:d453d1ba53e63992016af8',
    messagingSenderId: '393321453673',
    projectId: 'racroad',
    authDomain: 'racroad.firebaseapp.com',
    storageBucket: 'racroad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4kZwId4ZylE6AHIUiUq9Xuhy4xmDJlo',
    appId: '1:393321453673:android:c7a2d2821684a9b6016af8',
    messagingSenderId: '393321453673',
    projectId: 'racroad',
    storageBucket: 'racroad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFolj8E2CEheiq7aFlFVPF5KZX_QZ0aoQ',
    appId: '1:393321453673:ios:35c2f15a42a95615016af8',
    messagingSenderId: '393321453673',
    projectId: 'racroad',
    storageBucket: 'racroad.appspot.com',
    androidClientId: '393321453673-dg5cfmcmetuthirghh8mc1k568qp4163.apps.googleusercontent.com',
    iosClientId: '393321453673-cosio952o103tboghia8l3hnoih1f7eq.apps.googleusercontent.com',
    iosBundleId: 'com.medbuddy.racroad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFolj8E2CEheiq7aFlFVPF5KZX_QZ0aoQ',
    appId: '1:393321453673:ios:f973d3a671648a23016af8',
    messagingSenderId: '393321453673',
    projectId: 'racroad',
    storageBucket: 'racroad.appspot.com',
    androidClientId: '393321453673-dg5cfmcmetuthirghh8mc1k568qp4163.apps.googleusercontent.com',
    iosClientId: '393321453673-b4vosdnr9a775hs8s7lqjum9ef91ej6v.apps.googleusercontent.com',
    iosBundleId: 'com.medbuddy.racroadApp',
  );
}
